### ISSUE TITLE
Notifier does not resolve on Ubuntu

### ISSUE THREAD

**Issue by jrseliga** [jolicode/JoliNotif#37] opened 2017-07-13 03:03 UTC
### System
> *OS*: Ubuntu 17.04
> *PHP*: 7.0
> *JoliNotif*: 1.1.1

### Details
Notifications do not display

### Troubleshooting
If I force `$bestNotifier` to be `NotifySendNotifier` (line 37 in `Joli\JoliNotif\NotifierFactory`

```
$bestNotifier = new \Joli\JolieNotif\Notifier\NotifySendNotifier;
```
I do receive a desktop notification

### Issue
`isSupported()` is incorrectly returning `false` on `NotifySendNotifier`

**Comment by lyrixx** [comment] 2017-07-13 08:50
Hello @jrseliga.

Thanks for your bug report. It's very detailed and this is much appreciated.

The issue is command from symfony/process. There is a regression in this lib. I created [an issue](https://github.com/symfony/symfony/issues/23495) for that.

In the meantime, you can lock symfony/process to 3.2.* in your project to make it work.

**Comment by lyrixx** [comment] 2017-07-13 12:45
Hello. We have merged a PR that should solve your issue.

Thanks again for the report.

**Closed by lyrixx** 2017-07-13 12:45 UTC

**Comment by pyrech** [comment] 2017-07-13 12:55
FYI the fix is available in the 1.1.2 release :wink:
